// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"McKathlin_GameOver","status":true,"description":"MZ v1.3.1 Change what happens when the party dies or Game Over is called.","parameters":{"Party Death Common Event ID":"0","Show Game Over Scene":"true","After Game Over Common Event ID":"0"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"SRD_UltraBase","status":true,"description":"Contains code required for HUD Maker Ultra. Does not affect the RPG Maker codebase.","parameters":{}},
{"name":"EliMZ_Book","status":true,"description":"♦6.1.2♦ Essential plugin for all Eli plugins.","parameters":{"checkVersion":"true","updateErrorPrinter":"true","iterateEventList":"true","engine":"{\"styleOverflow\":\"false\",\"disableEffekseer\":\"false\",\"--- BUG FIXES ---\":\"\",\"fixBitmapStartLoad\":\"true\"}","playtest":"{\"gameFocus\":\"false\",\"enableGameWindowPosition\":\"false\",\"alignX\":\"left\",\"offsetX\":\"10\",\"alignY\":\"center\",\"offsetY\":\"10\",\"openDevTools\":\"false\",\"quickRestart\":\"true\",\"startFps\":\"false\"}"}},
{"name":"EliMZ_ButtonCommonEvents","status":true,"description":"♦1.7.3♦ Bind common events to keyboard/gamepad buttons!","parameters":{"presetKeys":"[]","presetKeysGamePad":"[]"}},
{"name":"SRD_HUDMakerUltra","status":true,"description":"Allows you to create and use HUDs for the map and battles.\r\nRequires the HUD Maker Ultra editor.","parameters":{"Auto-Reload HUD Data":"false","Enable Screenshots":"false","Hide Battle Status Window":"false","Hide Battle Selection Window":"false","Fade During Events":"true","Event Fade Opacity":"125","Fade Duration":"10","Map Visibility Code":"return true;","Battle Visibility Code":"return true;"}}
];
