// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"McKathlin_GameOver","status":true,"description":"MZ v1.3.1 Change what happens when the party dies or Game Over is called.","parameters":{"Party Death Common Event ID":"0","Show Game Over Scene":"true","After Game Over Common Event ID":"0"}}
];
